# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20181012_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojo_id',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_ninjas.Dojo'),
            preserve_default=False,
        ),
    ]
