# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0003_auto_20181012_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
