# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20181019_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnedJobs',
            new_name='OwnedJob',
        ),
    ]
