# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_users', '0003_auto_20181015_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='aaa', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='aaa', max_length=255),
        ),
    ]
