# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0002_auto_20181017_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='notes',
        ),
    ]
