# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0005_auto_20181017_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewsByUser', to='login_registration.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
